name       : libutempter
version    : 1.1.6
release    : 1
source     :
    - ftp://ftp.altlinux.org/pub/people/ldv/utempter/libutempter-1.1.6.tar.bz2 : b898565f31ced7e5c1fa0a2eaa0f6ff0ed862b5fe375d26375b64bfbdfeac397
license    : MIT # CHECK ME
component  : security 
summary    : A privileged helper for utmp and wtmp updates 
description: |
    Utempter is a utility that allows non-privileged applications such as
    terminal emulators to modify the utmp database without having to be
    setuid root. 
builddeps  :
        - gcc
setup      : | 
build      : |
    %make
install    : |
    %make_install
